//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBHOTELEntities4 : DbContext
    {
        public DBHOTELEntities4()
            : base("name=DBHOTELEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANCELACIONE> CANCELACIONES { get; set; }
        public virtual DbSet<CIUDADE> CIUDADES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual DbSet<EVENTO> EVENTOS { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<HABITACIONE> HABITACIONES { get; set; }
        public virtual DbSet<HABITACIONES_SERVICIOS> HABITACIONES_SERVICIOS { get; set; }
        public virtual DbSet<MODO_PAGO> MODO_PAGO { get; set; }
        public virtual DbSet<PERSONAL> PERSONALs { get; set; }
        public virtual DbSet<REGISTRO_ENTRADA_SALIDA> REGISTRO_ENTRADA_SALIDA { get; set; }
        public virtual DbSet<RESERVA> RESERVAS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<ROLES_POR_PERSONAL> ROLES_POR_PERSONAL { get; set; }
        public virtual DbSet<SEDE> SEDES { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOS { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_HABITACION> TIPO_HABITACION { get; set; }
    }
}
