//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int ID_DETALLE_FACTURA { get; set; }
        public Nullable<int> ID_FACTURA { get; set; }
        public Nullable<int> NUMERO_HABITACION { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }

        [JsonIgnore]
        public virtual FACTURA FACTURA { get; set; }

        [JsonIgnore]
        public virtual HABITACIONE HABITACIONE { get; set; }
    }
}
