//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_POR_PERSONAL
    {
        public int ID_REGISTRO { get; set; }
        public Nullable<int> ID_PERSONAL { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<bool> ACTIVO { get; set; }

        [JsonIgnore]
        public virtual PERSONAL PERSONAL { get; set; }

        [JsonIgnore]
        public virtual ROLE ROLE { get; set; }
    }
}
